### ISSUE TITLE
model download link dead

### ISSUE THREAD

**Issue by danpf** [gifford-lab/PUFFIN#4]
Hello,
If it isn't too much trouble could the download link for models.tar.gz file be updated?

it is currently:

http://gerv.csail.mit.edu/models.tar.gz

which i get a 2022-02-02 00:32:05 ERROR 403: Forbidden. error when trying to access.

Thank you!

**Comment by haoyangz** [comment]
@danpf we recently moved the data. Could you try the new link in the README?

**Comment by danpf** [comment]
@haoyangz That download link works! Thank you for the quick response! really appreciate it!

**Comment by shenlongchen** [comment]
@danpf 

Hello,
The new link is empty file. If it is convenient, could you share the file you downloaded？my email: shenlc1995@njust.edu.cn
Thank you!
